// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPerx0U_hq_ZFcPWUNLx8hSk3OwLMMtA',
    appId: '1:1086036338550:web:b680a64b0d3c3ec7e93c57',
    messagingSenderId: '1086036338550',
    projectId: 'tubes-91636',
    authDomain: 'tubes-91636.firebaseapp.com',
    storageBucket: 'tubes-91636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCffWoL5H2G3shnxEjHWR7yIuEn76KMou0',
    appId: '1:1086036338550:android:e61027c9a6ba7127e93c57',
    messagingSenderId: '1086036338550',
    projectId: 'tubes-91636',
    storageBucket: 'tubes-91636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbwpanmpqBK-pwQSDegU0o7e6vf6U452I',
    appId: '1:1086036338550:ios:93c350763737e98fe93c57',
    messagingSenderId: '1086036338550',
    projectId: 'tubes-91636',
    storageBucket: 'tubes-91636.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbwpanmpqBK-pwQSDegU0o7e6vf6U452I',
    appId: '1:1086036338550:ios:93c350763737e98fe93c57',
    messagingSenderId: '1086036338550',
    projectId: 'tubes-91636',
    storageBucket: 'tubes-91636.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtPerx0U_hq_ZFcPWUNLx8hSk3OwLMMtA',
    appId: '1:1086036338550:web:d0824ae35882e598e93c57',
    messagingSenderId: '1086036338550',
    projectId: 'tubes-91636',
    authDomain: 'tubes-91636.firebaseapp.com',
    storageBucket: 'tubes-91636.appspot.com',
  );
}
